# Site settings
title: Tabish Sada
email: sada.tabish@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hola! I read about code. I <3 data and manakish. I hoard blog posts, data sets, ebooks and almost anything I can lay my hands on.
baseurl: "/tabishsada.github.io" # the subpath of your site, e.g. /blog/
url: "http://tabishsada.github.io" # the base hostname & protocol for your site
twitter_username: tabish_sada
github_username:  tabishsada

# Build settings
markdown: kramdown
