# Site settings
title: Tabish Sada
email: sada.tabish@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hola! I code. I <3 data. I hoard blog posts, data sets, ebooks and almost anything I can lay my hands on.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tabishsada.com" # the base hostname & protocol for your site
twitter_username: tabish_sada
github_username:  tabishsada

lsi: false
# Build settings
markdown: kramdown
